# Generated by Django 3.2.9 on 2021-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriends',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
