# Generated by Django 3.2.9 on 2021-11-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userfriends_is_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='to_user',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='userfriends',
            old_name='from_user',
            new_name='user',
        ),
    ]
