# Generated by Django 3.2.9 on 2021-12-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211130_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='image_url',
            field=models.TextField(),
        ),
    ]
