# Generated by Django 3.2.9 on 2021-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211130_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
