# Generated by Django 3.2.9 on 2021-11-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211129_1518'),
        ('accounts', '0005_alter_userbooks_current_page'),
    ]

    operations = [
    ]
