# Generated by Django 3.2.9 on 2021-12-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoals',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
