# Generated by Django 3.2.9 on 2021-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingrouprequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
